[package]
name = "clr"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
rustclr = { path = "../" }

[profile.release]
strip = "debuginfo"
codegen-units = 1
opt-level = "z"
lto = true
